// Package evidencepack turns a HubbleOps WAL export into a compliance-ready evidence
// pack: a date-ranged summary of what engineering actions agents attempted, what
// HubbleOps enforced, an integrity proof of the underlying log, and an indicative
// mapping of each line item to change-governance controls. It is a reformat of data
// HubbleOps already records (WAL + receiptverify), not a new system.
package evidencepack

import (
	"encoding/json"
	"fmt"
	"sort"
	"strings"
	"time"

	"github.com/hubbleops/hubbleops/internal/receiptverify"
	"github.com/hubbleops/hubbleops/internal/wal"
)

// Control is a single control reference an evidence line item supports. The mapping is
// indicative supporting evidence, not a certification.
type Control struct {
	Framework string `json:"framework"`
	ID        string `json:"id"`
	Name      string `json:"name"`
}

func (c Control) String() string { return c.Framework + " " + c.ID }

// Indicative control references. SOC 2 uses the Common Criteria series; EU AI Act cites
// the article; ISO/IEC 42001 cites the Annex A control area (deliberately not a fabricated
// sub-clause number) so the mapping stays honest.
var (
	socCC2_2 = Control{"SOC 2", "CC2.2", "Internal communication of responsibilities"}
	socCC6_1 = Control{"SOC 2", "CC6.1", "Logical access / authorized actions"}
	socCC7_2 = Control{"SOC 2", "CC7.2", "Monitoring for anomalies"}
	socCC8_1 = Control{"SOC 2", "CC8.1", "Control over unauthorized changes/actions"}

	isoLogging   = Control{"ISO/IEC 42001", "Annex A (Logging)", "Automatic recording of AI system events"}
	isoOperation = Control{"ISO/IEC 42001", "Annex A (Operation)", "Operational controls for the AI system"}
	isoOversight = Control{"ISO/IEC 42001", "Annex A (Human oversight)", "Human oversight of AI decisions"}

	aiActArt9  = Control{"EU AI Act", "Article 9", "Risk management system"}
	aiActArt12 = Control{"EU AI Act", "Article 12", "Record-keeping / automatic logging"}
	aiActArt14 = Control{"EU AI Act", "Article 14", "Human oversight"}
	aiActArt15 = Control{"EU AI Act", "Article 15", "Accuracy and robustness"}
)

// Integrity is the cryptographic state of the underlying log over the selected range.
type Integrity struct {
	RecordsVerified     int  `json:"records_verified"`
	SignedReceipts      int  `json:"signed_receipts"`
	UnsignedReceipts    int  `json:"unsigned_receipts"`
	HashMismatches      int  `json:"hash_mismatches"`
	SignatureMismatches int  `json:"signature_mismatches"`
	HashChainIntact     bool `json:"hash_chain_intact"`
	SignaturesChecked   bool `json:"signatures_checked"`
	Verified            bool `json:"verified"`
}

// LineItem is one category of enforced/recorded activity with its supporting controls.
type LineItem struct {
	Category    string    `json:"category"`
	Count       int       `json:"count"`
	Description string    `json:"description"`
	Controls    []Control `json:"controls"`
}

// Pack is the full evidence pack.
type Pack struct {
	GeneratedAt          time.Time  `json:"generated_at"`
	Since                *time.Time `json:"since,omitempty"`
	Until                *time.Time `json:"until,omitempty"`
	Project              string     `json:"project,omitempty"`
	TotalActionDecisions int        `json:"total_action_decisions"`
	Blocked              int        `json:"blocked"`
	WouldBlock           int        `json:"would_block"`
	ApprovalRequired     int        `json:"approval_required"`
	Integrity            Integrity  `json:"integrity"`
	LineItems            []LineItem `json:"line_items"`
	Notice               string     `json:"notice"`
}

// Options control range/project filtering and how signatures are verified.
type Options struct {
	Since            time.Time // inclusive lower bound; zero = no lower bound
	Until            time.Time // exclusive upper bound; zero = no upper bound
	Project          string    // optional project filter
	ReceiptPublicKey string    // verify signatures with this published Ed25519 key
	ReceiptSecret    string    // or, for operators, the signing secret
}

const packNotice = "Supporting evidence generated by HubbleOps from a tamper-evident decision log. " +
	"Control mappings are indicative and intended to support an assessment; this pack is not an audit, " +
	"attestation, or certification."

// Build assembles the evidence pack from raw WAL records.
func Build(records []wal.Record, opts Options) Pack {
	filtered := filterRecords(records, opts)

	verifyReport := receiptverify.VerifyWithOptions(filtered, receiptverify.Options{
		ReceiptPublicKey: opts.ReceiptPublicKey,
		ReceiptSecret:    opts.ReceiptSecret,
	})
	summary := summarize(filtered)

	pack := Pack{
		GeneratedAt:          time.Now().UTC(),
		Project:              opts.Project,
		TotalActionDecisions: summary.TotalActionDecisions,
		Blocked:              summary.Blocked,
		WouldBlock:           summary.WouldBlock,
		ApprovalRequired:     summary.ApprovalRequired,
		Integrity: Integrity{
			RecordsVerified:     verifyReport.ActionReceipts,
			SignedReceipts:      verifyReport.SignedReceipts,
			UnsignedReceipts:    verifyReport.UnsignedReceipts,
			HashMismatches:      verifyReport.HashMismatches,
			SignatureMismatches: verifyReport.SignatureMismatches,
			HashChainIntact:     verifyReport.HashMismatches == 0 && verifyReport.ChainBrokenAt == -1 && verifyReport.MissingHashes == 0,
			SignaturesChecked:   opts.ReceiptPublicKey != "" || opts.ReceiptSecret != "",
			Verified:            verifyReport.Verified,
		},
		Notice: packNotice,
	}
	if !opts.Since.IsZero() {
		s := opts.Since.UTC()
		pack.Since = &s
	}
	if !opts.Until.IsZero() {
		u := opts.Until.UTC()
		pack.Until = &u
	}

	// The decision log itself is the headline record-keeping control, present whenever
	// there is any recorded activity.
	if summary.TotalActionDecisions > 0 || len(filtered) > 0 {
		pack.LineItems = append(pack.LineItems, LineItem{
			Category:    "Tamper-evident decision log",
			Count:       verifyReport.ActionReceipts,
			Description: "Every agent engineering-action decision was recorded to a hash-chained, signed write-ahead log.",
			Controls:    []Control{socCC7_2, isoLogging, aiActArt12},
		})
	}
	addLineItem(&pack, "High-risk engineering changes blocked", summary.Blocked,
		"Terraform, migration, deploy, or PR actions that matched a blocking policy were stopped before execution.",
		[]Control{socCC6_1, socCC8_1, isoOperation, aiActArt9, aiActArt14})
	addLineItem(&pack, "Engineering changes requiring approval", summary.ApprovalRequired,
		"Risky changes were paused for customer review before execution.",
		[]Control{socCC2_2, socCC8_1, isoOversight, aiActArt14})
	addLineItem(&pack, "Duplicate side-effect actions prevented", summary.DuplicateSideEffectDecisions,
		"Repeated consequential actions with a stable idempotency key were caught before re-execution.",
		[]Control{socCC8_1, isoOperation, aiActArt15})

	return pack
}

func addLineItem(pack *Pack, category string, count int, description string, controls []Control) {
	if count <= 0 {
		return
	}
	pack.LineItems = append(pack.LineItems, LineItem{
		Category:    category,
		Count:       count,
		Description: description,
		Controls:    controls,
	})
}

func filterRecords(records []wal.Record, opts Options) []wal.Record {
	out := make([]wal.Record, 0, len(records))
	for _, rec := range records {
		if opts.Project != "" && rec.Project != opts.Project {
			continue
		}
		if !opts.Since.IsZero() && rec.Time.Before(opts.Since) {
			continue
		}
		if !opts.Until.IsZero() && !rec.Time.Before(opts.Until) {
			continue
		}
		out = append(out, rec)
	}
	return out
}

func decisionKey(rec wal.Record) string {
	if rec.DecisionID != "" {
		return rec.DecisionID
	}
	if rec.RecordHash != "" {
		return rec.RecordHash
	}
	return fmt.Sprintf("%s|%s|%s|%s", rec.Project, rec.SessionID, rec.ToolSignature, rec.DecisionStage)
}

type summaryStats struct {
	TotalActionDecisions         int
	Blocked                      int
	WouldBlock                   int
	ApprovalRequired             int
	DuplicateSideEffectDecisions int
}

func summarize(records []wal.Record) summaryStats {
	seenDecisions := map[string]struct{}{}
	blocked := map[string]struct{}{}
	wouldBlock := map[string]struct{}{}
	approval := map[string]struct{}{}
	duplicates := map[string]struct{}{}
	for _, rec := range records {
		if rec.DecisionID == "" {
			continue
		}
		key := decisionKey(rec)
		seenDecisions[key] = struct{}{}
		switch strings.ToLower(strings.TrimSpace(firstNonEmpty(rec.Decision, rec.LoopAction))) {
		case "block":
			blocked[key] = struct{}{}
		case "shadow_would_block":
			wouldBlock[key] = struct{}{}
		case "require_approval":
			approval[key] = struct{}{}
		}
		if strings.Contains(rec.LoopSignalsFired, "duplicate_side_effect") {
			duplicates[key] = struct{}{}
		}
	}
	return summaryStats{
		TotalActionDecisions:         len(seenDecisions),
		Blocked:                      len(blocked),
		WouldBlock:                   len(wouldBlock),
		ApprovalRequired:             len(approval),
		DuplicateSideEffectDecisions: len(duplicates),
	}
}

// RenderJSON returns the machine-readable evidence pack.
func RenderJSON(pack Pack) ([]byte, error) {
	return json.MarshalIndent(pack, "", "  ")
}

// RenderMarkdown returns the human-readable evidence pack a compliance reviewer can read.
func RenderMarkdown(pack Pack) string {
	var b strings.Builder
	b.WriteString("# HubbleOps Evidence Pack\n\n")
	fmt.Fprintf(&b, "- Generated: %s\n", pack.GeneratedAt.Format(time.RFC3339))
	if pack.Project != "" {
		fmt.Fprintf(&b, "- Project: `%s`\n", pack.Project)
	}
	fmt.Fprintf(&b, "- Period: %s\n", periodString(pack))
	fmt.Fprintf(&b, "- Agent actions recorded: %d\n", pack.TotalActionDecisions)
	fmt.Fprintf(&b, "- Actions blocked: %d; approvals required: %d; would-block in shadow mode: %d\n", pack.Blocked, pack.ApprovalRequired, pack.WouldBlock)

	b.WriteString("\n## Log integrity\n\n")
	in := pack.Integrity
	fmt.Fprintf(&b, "- Hash chain intact: %s\n", yesNo(in.HashChainIntact))
	if in.SignaturesChecked {
		fmt.Fprintf(&b, "- Signed receipts verified: %d (mismatches: %d)\n", in.SignedReceipts, in.SignatureMismatches)
	} else {
		fmt.Fprintf(&b, "- Signed receipts: %d (signatures not checked — supply a receipt public key to verify)\n", in.SignedReceipts)
	}
	fmt.Fprintf(&b, "- Overall verified: %s\n", yesNo(in.Verified))

	b.WriteString("\n## Controls evidenced\n\n")
	if len(pack.LineItems) == 0 {
		b.WriteString("No recorded activity in the selected period.\n")
	} else {
		b.WriteString("| Activity | Count | Supports |\n")
		b.WriteString("| --- | ---: | --- |\n")
		for _, item := range pack.LineItems {
			fmt.Fprintf(&b, "| %s | %d | %s |\n", item.Category, item.Count, controlList(item.Controls))
		}
		b.WriteString("\n### Detail\n\n")
		for _, item := range pack.LineItems {
			fmt.Fprintf(&b, "- **%s** (%d): %s\n", item.Category, item.Count, item.Description)
		}
	}

	fmt.Fprintf(&b, "\n---\n\n_%s_\n", pack.Notice)
	return b.String()
}

func periodString(pack Pack) string {
	switch {
	case pack.Since != nil && pack.Until != nil:
		return fmt.Sprintf("%s to %s", pack.Since.Format("2006-01-02"), pack.Until.Format("2006-01-02"))
	case pack.Since != nil:
		return fmt.Sprintf("since %s", pack.Since.Format("2006-01-02"))
	case pack.Until != nil:
		return fmt.Sprintf("until %s", pack.Until.Format("2006-01-02"))
	default:
		return "all available records"
	}
}

func controlList(controls []Control) string {
	parts := make([]string, 0, len(controls))
	for _, c := range controls {
		parts = append(parts, c.String())
	}
	sort.Strings(parts)
	return strings.Join(parts, "; ")
}

func yesNo(v bool) string {
	if v {
		return "yes"
	}
	return "no"
}

func firstNonEmpty(values ...string) string {
	for _, value := range values {
		if strings.TrimSpace(value) != "" {
			return value
		}
	}
	return ""
}
